=== jcvegab/jcvegab-portfolio/schemas/config.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Configuration",
  "description": "This file contains the configuration for the website, including the header, footer, and other settings.",
  "type": "object",
  "required": ["title", "header", "footer"],
  "additionalProperties": false,
  "properties": {
    "$schema": {
      "description": "A field for the JSON schema specification: https://json-schema.org/",
      "anyOf": [{ "$ref": "#/$defs/Schema" }, { "type": "null" }]
    },
    "title": { "type": "string" },
    "color_scheme": {
      "type": "string",
      "enum": ["light", "dark"]
    },
    "accent_color": { "type": "string" },
    "path_prefix": { "type": "string" },
    "favicon": { "type": "string" },
    "domain": { "type": "string" },
    "header": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "title": { "type": "string" },
        "has_nav": { "type": "boolean" },
        "logo_img": { "type": "string" },
        "logo_img_alt": { "type": "string" },
        "nav_links": { "$ref": "#/$defs/ActionItem" }
      }
    },
    "footer": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "content": { "type": "string" },
        "has_social": { "type": "boolean" },
        "links": { "$ref": "#/$defs/ActionLinkItem" },
        "social_links": { "$ref": "#/$defs/ActionItem" }
      }
    }
  },
  "$defs": {
    "Schema": { "type": "string" },
    "IconVariant": {
      "type": "string",
      "enum": [
        "dribbble",
        "facebook",
        "github",
        "instagram",
        "linkedin",
        "pinterest",
        "twitter",
        "youtube",
        "vimeo"
      ]
    },
    "ActionItem": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["label", "url"],
        "additionalProperties": false,
        "properties": {
          "label": { "type": "string" },
          "url": { "type": "string" },
          "style": {
            "type": "string",
            "enum": ["link", "button", "icon"]
          },
          "icon": { "$ref": "#/$defs/IconVariant" },
          "new_window": { "type": "boolean" },
          "no_follow": { "type": "boolean" }
        }
      }
    },
    "ActionLinkItem": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["url", "label"],
        "additionalProperties": false,
        "properties": {
          "url": { "type": "string" },
          "label": { "type": "string" },
          "new_window": { "type": "boolean" },
          "no_follow": { "type": "boolean" }
        }
      }
    }
  }
}

=== jcvegab/jcvegab-portfolio/content/data/config.json
{
  "$schema": "../../schemas/config.schema.json",
  "title": "Configuration",
  "path_prefix": "/",
  "color_scheme": "light",
  "accent_color": "blue",
  "header": {
    "title": "JCVEGAB",
    "has_nav": true,
    "nav_links": [
      {
        "label": "Inicio",
        "url": "/",
        "style": "link"
      },
      {
        "label": "Portafolio",
        "url": "/portfolio/",
        "style": "link"
      },
      {
        "label": "Acerca",
        "url": "/about/",
        "style": "link"
      },
      {
        "label": "Contacto",
        "url": "/contact/",
        "style": "link"
      }
    ],
    "logo_img": "/images/logo_full.png"
  },
  "footer": {
    "content": "Joseph Vega Blacido @jcvegab | Todos los derechos reservados &copy; 2026.",
    "has_social": true,
    "social_links": [
      {
        "label": "Github",
        "url": "https://www.github.com/jcvegab",
        "style": "icon",
        "icon": "github",
        "new_window": true,
        "no_follow": false
      },
      {
        "label": "LinkedIn",
        "url": "https://www.linkedin.com/in/joseph-vegab",
        "style": "icon",
        "icon": "linkedin",
        "new_window": true
      },
      {
        "label": "Twitter",
        "url": "https://twitter.com/jcvegab",
        "style": "icon",
        "icon": "twitter",
        "new_window": true
      },
      {
        "label": "Instagram",
        "url": "https://www.instagram.com/jcvegab_",
        "style": "icon",
        "icon": "instagram",
        "new_window": true
      }
    ]
  },
  "domain": "https://jcvegab.dev",
  "favicon": "/images/favicon.png"
}
